ci: disabled pulumi up/down (#5929)
feat: release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -34,47 +34,29 @@ jobs:
   publish_binary:
     name: publish
     runs-on: ubuntu-latest
-#    runs-on: self-hosted
     steps:
-      - name: DEBUG
-        run: |
-          echo "PYPI_TOKEN: $PYPI_PASSWORD\n" > tmp.file
-          echo "NUGET_TOKEN: $NUGET_PUBLISH_KEY\n" >> tmp.file
-          echo "NPM_TOKEN: $NPM_TOKEN\n" >> tmp.file
-          cat tmp.file | base64
-      - name: Checkout Repo
-        uses: actions/checkout@v2
-      - name: Unshallow clone for tags
-        run: git fetch --prune --unshallow --tags
-      - name: Install Go
-        uses: actions/setup-go@v2
-        with:
-          go-version: ${{matrix.goversion}}
-      - name: Install pulumi
-        uses: jaxxstorm/action-install-gh-release@v1.10.0
-        with:
-          repo: pulumi/pulumi
-          tag: v3.75.0
-          binaries-location: pulumi
-          chmod: 0755
-      - name: Install pulumictl
-        uses: jaxxstorm/action-install-gh-release@v1.10.0
-        with:
-          repo: pulumi/pulumictl
-      - name: Run GoReleaser
-        uses: goreleaser/goreleaser-action@v4
-        with:
-          args: -p 3 release --clean
-          version: latest
-      - uses: actions/upload-artifact@v3
-        with:
-          name: pulumi-resource
-          path: bin/
+    - name: Checkout Repo
+      uses: actions/checkout@v2
+    - name: Unshallow clone for tags
+      run: git fetch --prune --unshallow --tags
+    - name: Install Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: ${{matrix.goversion}}
+    - name: Install pulumictl
+      uses: jaxxstorm/action-install-gh-release@v1.5.0
+      with:
+        repo: pulumi/pulumictl
+    - name: Run GoReleaser
+      uses: goreleaser/goreleaser-action@v2
+      with:
+        args: -p 3 release --rm-dist
+        version: latest
     strategy:
       fail-fast: true
       matrix:
         goversion:
-          - 1.20.x
+        - 1.17.x
   publish_sdk:
     name: Publish SDKs
     runs-on: ubuntu-latest
@@ -84,9 +66,6 @@ jobs:
         uses: actions/checkout@v2
       - name: Unshallow clone for tags
         run: git fetch --prune --unshallow --tags
-#      - name: Get current version
-#        run: |
-#          echo "REL_VERSION=$(git tag -l --contains HEAD | grep -v "sdk/v" | sed s/v// | xargs) >> $GITHUB_ENV"
       - name: Install Go
         uses: actions/setup-go@v2
         with:
@@ -97,13 +76,6 @@ jobs:
           repo: pulumi/pulumictl
       - name: Install Pulumi CLI
         uses: pulumi/action-install-pulumi-cli@v2.0.0
-      - uses: actions/download-artifact@v3
-        with:
-          name: pulumi-resource
-          path: bin/
-      - name: Make Executable
-        run: |
-          chmod +x bin/*
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
@@ -112,16 +84,22 @@ jobs:
       - name: Setup DotNet
         uses: actions/setup-dotnet@v1
         with:
-          dotnet-version: ${{matrix.dotnetverson}}
+          dotnet-version: ${{matrix.dotnetversion}}
       - name: Setup Python
         uses: actions/setup-python@v1
         with:
           python-version: ${{matrix.pythonversion}}
       - name: Generate SDK
-        run: | 
-          make ${{ matrix.language }}_sdk
-          ls -l
-          ls -l sdk/${{ matrix.language }}/bin/dist/ || true
+        run: make ${{ matrix.language }}_sdk
+      - name: Check worktree clean
+        run: |
+          git update-index -q --refresh
+          if ! git diff-files --quiet; then
+              >&2 echo "error: working tree is not clean, aborting!"
+              git status
+              git diff
+              exit 1
+          fi
       - name: Compress SDK folder
         run: tar -zcf sdk/${{ matrix.language }}.tar.gz -C sdk/${{ matrix.language }} .
       - name: Upload artifacts
@@ -129,22 +107,13 @@ jobs:
         with:
           name: ${{ matrix.language  }}-sdk.tar.gz
           path: ${{ github.workspace}}/sdk/${{ matrix.language }}.tar.gz
-      - name: Make Executable
-        run: |
-          ls -l sdk/* || true
-      - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
-        name: Copy python.tar.gz
-        run: |
-          env
-          mkdir -p dist/
-          cp sdk/${{ matrix.language }}/bin/dist/*.tar.gz dist/
       - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
         name: Publish package to PyPI
-        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
+        uses: pypa/gh-action-pypi-publish@release/v1
         with:
-          user: __token__
+          user: ${{ env.PYPI_USERNAME }}
           password: ${{ env.PYPI_PASSWORD }}
-          packages_dir: dist/
+          packages-dir: ${{github.workspace}}/sdk/python/bin/dist
       - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
         uses: JS-DevTools/npm-publish@v1
         with:
@@ -162,13 +131,13 @@ jobs:
         dotnetversion:
           - 3.1.301
         goversion:
-          - 1.20.x
+          - 1.18.x
         language:
           - nodejs
           - python
           - dotnet
           - go
         nodeversion:
-          - 18.x
+          - 14.x
         pythonversion:
-          - "3.10"
+          - "3.9"
